# Generated by Django 4.0.4 on 2022-05-31 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.TextField(max_length=10000, verbose_name='Содержание заметки'),
        ),
        migrations.AlterField(
            model_name='note',
            name='update_at',
            field=models.DateField(auto_now_add=True, verbose_name='Время обновления заметки'),
        ),
    ]
