# Generated by Django 4.0.4 on 2022-06-02 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0002_alter_note_note_alter_note_update_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-create_at', 'important_status']},
        ),
    ]
