# Generated by Django 4.0.4 on 2022-06-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0003_alter_note_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-create_at', 'important_status'], 'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
        migrations.RemoveField(
            model_name='note',
            name='public',
        ),
        migrations.AddField(
            model_name='note',
            name='public_status',
            field=models.BooleanField(default=False, verbose_name='Публичная'),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_status',
            field=models.IntegerField(choices=[(0, 'Активно'), (1, 'Отложено'), (2, 'Выполнено')], default=0, verbose_name='Статус'),
        ),
    ]
